### ISSUE TITLE
Restructuring replicaset tasks

### ISSUE THREAD

**Issue by vanyarock01** [tarantool/ansible-cartridge#101]
## Summary

Pull replicaset management tasks from `main.yml` to a separate file (`replicasets.yml`) and and do not apply tags to this task list.

## Motivation

In our case, we have custom roles for deploying, no systemd and this role requires for only topology management. Now, to use the role only for managing the replicasets, you must specify command line tags. This makes it difficult to integrate this role into another playbook, since it is impossible to specify tags from the playbook, only from the command line. 

## Design Detail

Tasks with the tag `cartridge-replicasets` transfer to new file `replicases.yml`. In `main.yml` include the list of replicasets tasks and tag them. Tasks inside `replicasets.yml` do not tag `cartridge-replicasets`.

```yaml
- name: Cartridge cluster management
  include_tasks: replicasets.yml
  tags: cartridge_replicasets
```

In external playbook replicasets tasks importing will look like this:

```yaml
tasks:
  - name: Run ansible-cartridge role
    import_role:
      name: ansible-cartridge
      tasks_from: replicasets
```

Tasks from [doc page](https://docs.ansible.com/ansible/latest/modules/import_role_module.html#parameter-tasks_from)

## Drawbacks

When crossing tags, you will need to duplicate tasks from `main.yml` to `replicasets.yml`. Now it is only [Select one not expelled instance](https://github.com/tarantool/ansible-cartridge/blob/38add5def5b2d7d030d2b7afc1e747eccd9a3c79/tasks/main.yml#L72) task.
