### ISSUE TITLE
RFC:  Split Monolith

### ISSUE THREAD

**Issue by dokshina** [tarantool/ansible-cartridge#141]
See #135

**Comment by hackallcode** [comment]
# Role splitting

We can split the role using several variants:
- use many different tags;
- do multiple roles;
- make own mechanism of splitting into sections.

## Using many different tags

### Pros:
- this approach allows you to use different parts of the role, both one and several.

### Cons:
- it is impossible to change the order of execution of different parts with one launch of Anisble, only with several starts;
- to use custom tasks, you also need to run Anisble several times (i.e., to use a custom task in the middle of a role, you should start a role with tags, then a custom task, then again a role with tags);
- impossible to use `ansible-cartridge` variables.

## Using multiple roles

### Pros:
- possible to use any part of the role in any order;
- possible to use custom task anywhere in the role.

### Cons:
- you will have to install all roles separately, which is inconvenient for user;
- difficult to change the list of roles and keep them up to date;
- impossible to use `ansible-cartridge` variables.

## Custom Mechanism

It is proposed to divide the role into many sections and combine them using a scenario in the config:
```yaml
cartridge_scenario:
  - load_package
  - install_package
  - setup_systemd_config
  - start_instance
  - connect_to_membership
  - edit_topology
  - expel_instance
  - setup_app_auth
  - setup_app_config
  - bootstrap
  - manage_failover
```

Accordingly, this scenario can be rewritten via `vars`, which allows you to run a role several times in one playbook with different scenarios:
```yaml
tasks:
  - name: Import Tarantool Cartridge
    import_role:
      name: tarantool.cartridge
    vars:
      cartridge_scenario:
        - setup_app_config
  - name: Import Tarantool Cartridge again
    import_role:
      name: tarantool.cartridge
    vars:
      cartridge_scenario:
        - bootstrap
        - manage_failover
```

To use custom tasks in the role configuration, it is proposed to specify the folder with user sections through the option in the configuration:
```yaml
cartridge_custom_sections_dir: "./sections"
```
YAML files will be searched in the specified folder, and then the names of the files will be taken for the section names: the file `./tasks/my_task.yml` will be imported as the section `my_task`. These sections can also be used in `cartridge_scenario`.

It is also proposed to add the ability to import files with custom tasks from arbitrary places with arbitrary names:
```yaml
cartridge_custom_sections:
  - name: my_task
    file: "../common_sections/my_task.yml"
  - name: bootstrap
    file: "./my_sections/bootstrap.yml"
```
These sections can also be used in `cartridge_scenario`.

If the section names conflict, the section with a higher priority will be executed (allows you to overwrite any role section with a custom one). Priority:
- the section described in `cartridge_custom_sections`;
- section from the folder specified in `cartridge_custom_sections_dir`;
- role section.

### Pros:
- possible to use any part of the role in any order;
- possible to use custom task anywhere in the role;
- possible to overwrite role tasks;
- possible to use `ansible-cartridge` variables;
- only one role needs to be installed.
