### ISSUE TITLE
[2pt] Impossible to skip role using tags

### ISSUE THREAD

**Issue by hackallcode** [tarantool/ansible-cartridge#156]
I have several tasks in my playbook. One of them is importing the anisble-cartridge role.
I made a tag for this task like this:
```yaml
- name: Deploy Tarantool Cartridge app
  hosts: cartridge_group
  become: true
  any_errors_fatal: true
  tags:
    - cartridge
  tasks:
    - name: Import Tarantool Cartridge role
       import_role:
         name: tarantool.cartridge
```
After that, I start the playbook with the `-t some-tag` parameter. I expected the role installation to be skipped completely, but in the end I get error like this:
```
fatal: [host_name]: FAILED! => {"msg": "The conditional check 'ansible_os_family not in [\"RedHat\", \"Debian\"]' failed. The error was: error while evaluating conditional (ansible_os_family not in [\"RedHat\", \"Debian\"]): 'ansible_os_family' is undefined\n\nThe error appears to be in '.ansible/roles/tarantool.cartridge/tasks/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Check distribution\n  ^ here\n"}
```

I think this is because you are using `tags: always` instead list of tags.
