### ISSUE TITLE
[2pt] Impossible to use one of tags when use in playbook

### ISSUE THREAD

**Issue by hackallcode** [tarantool/ansible-cartridge#170]
I have several tasks in my playbook. One of them is importing the anisble-cartridge role.
I made a tag for this task like this:
```yaml
- name: Deploy Tarantool Cartridge app
  hosts: cartridge_group
  tags: cartridge
  tasks:
    - name: Import Tarantool Cartridge role
       import_role:
         name: tarantool.cartridge
```
After that, I start the playbook with the `-t cartridge-instances` parameter. I expected the role will be execute tasks with `cartridge-instances` tag, but in the end I get error like this:
```
fatal: [host_name]: FAILED! => {"msg": "The conditional check 'ansible_os_family not in [\"RedHat\", \"Debian\"]' failed. The error was: error while evaluating conditional (ansible_os_family not in [\"RedHat\", \"Debian\"]): 'ansible_os_family' is undefined\n\nThe error appears to be in '.ansible/roles/tarantool.cartridge/tasks/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Check distribution\n  ^ here\n"}
```

This is because I want to use `tags: cartridge` for task with role import. Therefore, gathering of facts occurs only if the `cartridge` tag is specified.

Let's make a facts gathering task that will be completed if the facts were not gathered earlier and one of our tags is specified.
