### ISSUE TITLE
[2pt] Let's use some default scenarios instead of tags

### ISSUE THREAD

**Issue by hackallcode** [tarantool/ansible-cartridge#217]
Before scenarios were added, tags were used to partially run of role. Now, with the scenarios added, you can decide for yourself which steps you want to start. But sometimes new steps can be added to the default script. If a step is added to an existing logical group of steps (for example, a new step for configuring an application), then those users who use their scenarios (for example, for configuring an application) will not have this step and they will have to add this step manually.

Let's make some default scripts (for example, "package update", "topology configuration", "application configuration"). And the user will be able to choose one of the supported scenarios.

It is proposed to make a table with scenarios to which the users can add their scenarios. Example of role defaults:

```yaml
cartridge_scenario_name: 'default'
cartridge_role_scenarios:
  default:
    - deliver_package
    - update_package
    - update_instance
    - configure_instance
    - restart_instance
    - wait_instance_started
    - connect_to_membership
    - edit_topology
    - cleanup_expelled
    - configure_auth
    - configure_app_config
    - bootstrap_vshard
    - configure_failover
  configure_instances:
    - deliver_package
    - update_package
    - update_instance
    - configure_instance
    - restart_instance
    - wait_instance_started
  configure_topology:
    - connect_to_membership
    - edit_topology
    - cleanup_expelled
  configure_app:
    - configure_auth
    - configure_app_config
    - bootstrap_vshard
    - configure_failover
```

Example of user playbook with custom scenarios:
```yaml
---
- name: Deploy Tarantool Cartridge app
  hosts: all
  vars:
    cartridge_custom_scenarios:
      update_instance_tgz:
        - update_instance
        - configure_instance
        - restart_instance
        - wait_instance_started
      configure_topology:
        - edit_topology
        - cleanup_expelled
  tasks:
    - name: Update package
      import_role:
        name: tarantool.cartridge
      vars:
        cartridge_scenario_name: 'update_instance_tgz' # new user scenario
    - name: Configure cluster
      import_role:
        name: tarantool.cartridge
      vars:
        cartridge_scenario_name: 'configure_topology' # changed role scenario
    - name: Configure application
      import_role:
        name: tarantool.cartridge
      vars:
        cartridge_scenario_name: 'configure_app' # default scenario
    - name: Custom implace scenario
      import_role:
        name: tarantool.cartridge
      vars:
        cartridge_scenario:
          - wait_instance_started
```

**Comment by vasiliy-t** [comment]
Playbooks composition is nice feature. 
But `scenario`s introduce new concept unique to this role. It is more common to [use imports and includes](https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse.html#playbooks-reuse) to compose/reuse roles and it's parts. I suggest scenarios implementation to be compatible with ansible imports so that scenarios based yaml: 

```yaml
 - name: Custom implace scenario
      import_role:
        name: tarantool.cartridge
      vars:
        cartridge_scenario:
          - wait_instance_started
```

and ansible default imports based:

```yaml
 - name: Custom implace scenario
      import_role:
        name: tarantool.cartridge
        tasks_from: wait_instance_started
```
do the very same thing.
