### ISSUE TITLE
[2pt] Add a step to patch instance parameters in runtime

### ISSUE THREAD

**Issue by dokshina** [tarantool/ansible-cartridge#253]
Sometimes we want to change some `box.cfg` parameters in runtime and/or in the configuration files. 
It can be convenient to do it like this:

```yaml
- name: Set replication_connect_quorum to zero
  hosts: "*storage*"
  become: true
  gather_facts: no
  roles:
    - tarantool.cartridge
  vars:
    cartridge_scenario:
      - set_box_cfg_params
    cartridge_box_cfg_params:
      replication_connect_quorum: 0
    runtime_only: true
    # persist_only: true
```

Parameters are set to specified values for all instances specified for the play.

By default, parameters are changed in configuration files.
If some of them can be changed in runtime - it's changed.
In this case, `need_restart` is set to `true` if the instance should be restarted to apply changes.

If `runtime_only` is set, then the step tries to change ALL passed parameters in runtime for each instance.
If `persist_only` is set, all parameters are changed only in the configuration files.
