### ISSUE TITLE
Expelled instance status "left" is not taken into account

### ISSUE THREAD

**Issue by BakhtiarovSergey** [tarantool/ansible-cartridge#349]
ansible 2.9.6
ansible-cartridge 1.10.0

Steps to reproduce:
1. Deploy cluster on 1st server via role
2. Add instances of 2nd server in YAML
3. Expand cluser on 2 servers via role
4. Expel instances of 1st server
5. Remove instances of 1st server from YAML
6. Re-apply role

Log sample ("storage-1-replica-1" expelled):
```
TASK [tarantool.cartridge : Select control instance to manage topology and configuration via storage-1d-replica-1] **********************************************
fatal: [storage-1d -> 192.168.113.48]: FAILED! => {"changed": false, "msg": "Membership contains instance storage-1-replica-1 that isn't described in inventory"}
```
Fragment of `require('membership').members()`
```yaml
...
  192.168.113.47:3301:
    payload: {'state': 'ConfiguringRoles', 'uuid': 'bf560e0d-ebff-4161-9557-d8e8b195edd5',
      'alias': 'storage-1-replica-1'}
    uri: 192.168.113.47:3301
    clock_delta: 1420.5
    status: left
    incarnation: 70
    timestamp: 1623769086216935
...
```

**Comment by BakhtiarovSergey** [comment]
```yaml
# Role scenario configuration

cartridge_scenario: null
cartridge_custom_steps_dir: null
cartridge_custom_steps: []

cartridge_scenario_name: 'default'
cartridge_custom_scenarios: {}
cartridge_role_scenarios:
  default:
    - deliver_package
    - update_package
    - update_instance
    - configure_instance
    - restart_instance
    - wait_instance_started
    - connect_to_membership
    - edit_topology
    - cleanup_expelled # present
    - configure_auth
    - upload_app_config
    - configure_app_config
    - bootstrap_vshard
    - configure_failover
    - wait_members_alive
    - wait_cluster_has_no_issues
    - cleanup
   ```
