### ISSUE TITLE
Ignore old instances from membership

### ISSUE THREAD

**Issue by hackallcode** [tarantool/ansible-cartridge#354]
Sometimes in membership several copies of one instance:
```yaml
old_uri:
  payload:
    uuid: my-uuid
    state: RolesConfigured
    alias: my-alias
  uri: old_uri
  status: dead
  incarnation: 576

new_uri:
  payload:
    uuid: my-uuid
    state: RolesConfigured
    alias: my-alias
  uri: new_uri
  status: alive
  incarnation: 1203
```

We should use only one with maximum `incarnation`. Sometimes old instances has no payload.
