### ISSUE TITLE
Vault secrets are not decrypted

### ISSUE THREAD

**Issue by knazarov** [tarantool/ansible-cartridge#64]
Snippet from my inventory:

```yaml
---
all:
  vars:
    cartridge_cluster_cookie: !vault |
      $ANSIBLE_VAULT;1.2;AES256;knazarov
      63393238306532306338376334393136343437626636393465313738643363623133663239386435
      6661303861613830616233343334343162653433316235620a343937313538303235626464386561
      66393730343965353932313732383736376135633639613737646434313261373862636430303364
      3137333463643730610a643163333463333138323161373563373038383839323338343839353266
      3630
```
If I print this variable like this, It is shown unencrypted:

```yaml
---
- name: Deploy my Tarantool Cartridge app
  hosts: all
  become: true
  become_user: root
  tasks:
  - name: debug password
    debug:
      msg: "{{ cartridge_cluster_cookie }}"
```

But if I try to use ansible-cartridge, it doesn't decrypt this variable, when interpolating it into the configuration file. I guess that's because you do it with python, and not using jinja templates.
