### ISSUE TITLE
Add ability to specify cluster topology in the playbook

### ISSUE THREAD

**Issue by Kasen** [tarantool/ansible-cartridge#76]
I want to set my topology in the my playbook because I have generated inventory and can't change it.
I want something like that:

```yaml
- hosts: app
  remote_user: ansible
  become: yes
  tasks:
  - name: Import Tarantool Cartridge role
    import_role:
      name: tarantool.cartridge
  vars:
    instances:
      app1:
        advertise_uri: 'localhosts:3301'
        http_port: 8081
      app2:
        advertise_uri: 'localhosts:3302'
        http_port: 8082

- hosts: storage
  remote_user: ansible
  become: yes
  tasks:
  - name: Import Tarantool Cartridge role
    import_role:
      name: tarantool.cartridge
  vars:
    instances:
      storage1:
        advertise_uri: 'localhosts:3303'
        http_port: 8083
        replica_set: storage_01
        leader: true
      storage2:
        advertise_uri: 'localhosts:3304'
        http_port: 8084
        replica_set: storage_01
```
