### ISSUE TITLE
Unable to set cartridge_package_name using lookup plugin

### ISSUE THREAD

**Issue by RunsFor** [tarantool/ansible-cartridge#78]
This setup is not working:

```yaml
  - name: Import Tarantool Cartridge role
    import_role:
      name: tarantool.cartridge
    vars:
      cartridge_package_path: "{{ lookup('fileglob', '*.rpm') }}"
```

Debug print tells this:

```
TASK [tarantool.cartridge : Debug] *****************************************************************
ok: [frontend] => {
    "cartridge_package_path": []
}

TASK [tarantool.cartridge : Copy RPM] **************************************************************
fatal: [frontend]: FAILED! => {"changed": false, "msg": "src (or content) is required"}
```
