### ISSUE TITLE
Support stateful failover

### ISSUE THREAD

**Issue by dokshina** [tarantool/ansible-cartridge#95]
This is the last part of https://github.com/tarantool/cartridge/issues/714

Remind, that stateboard systemd unit (`/etc/systemd/system/<appname>-stateboard.service`) is delivered in application package **only** if application contains `stateboard.init.lua` in it's root directory.

It reads configuration from `<appname>-stateboard` section in `/etc/tarantool/conf.d` files.

**Comment by dokshina** [comment]
## RFC

### What do we have now?

`cartridge_failover` is a boolean variable that enables/disables eventual failover.

It uses `cartridge.admin_enable_failover` and `cartridge.admin_disable_failover `.

### What do we need to support?

Now cartridge supports one more failover mode - `stateful`.

`cartridge.admin_{enable,disable}_failover` functions are deprecated since cartridge v2.1.0 in favor of `cartridge.failover_set_params` since failover has two different modes.

When using stateful failover, the `leader`concept is separated from `failover_priority`. User can promote a leader for replicaset, and failover priority specifies the order of instances to become a leader on leader failure.

Moreover, using stateful failover requires starting special instance called `stateboard`. 
This instance is used as a `tarantool` state provider (now it's the only one supported provider).

### Setting stateful failover parameters

I suggest deprecating `cartridge_failover` boolean parameter in favor to `cartridge_failover_params`:

```yaml
cartridge_failover_params:
  mode: one-of ["eventual", "stateful", "disabled"]
  state_provider: one-of ["stateboard"] # required for `stateful` mode
  stateboard_params: # required for `stateboard` state provider
    uri: string # required
    password: string  # required
```

Role should perform `cartridge.VERSION` check to make sure that `cartridge.failover_set_params` can be used.

### Leader promotion

Leader promotion should be performed manually using Web UI, GraphQL API or Lua API.

### Starting stateboard instance.

I suggest adding `stateboard` variable that indicates that instance is a stateboard.
For stateboard instance only these variables are allowed:

- `cartridge_app_name`: app name is `myapp`, not `myapp-stateboard`;
- `cartridge_package_path`: stateboard is delivered in the application package;
- `cartridge_enable_tarantool_repo`;
- `config`: saved to `/etc/tarantool/conf.d/myapp-stateboard.yml`, section `myapp-stateboard`;
- `restarted`;
- `instance_start_timeout`.

Other variables are ignored (e.g. it can be useful to place `cartridge_cluster_cookie` in `all` section).

The role is responsible for getting stateboard systemd service name by application name.

Example:

```yaml
---
all:
  vars:
    cartridge_package_path: ./myapp-1.0.0-0.rpm
    cartridge_cluster_cookie: secret-cookie
    cartridge_defaults:
      log_level: 1

  hosts:  # instances
    my-lovely-stateboard:  # name does not matter
      ansible_host: 172.19.0.2
      ansible_user: vagrant
      stateboard: true  # this matters -> instance is a stateboard
      restarted: true
      config: 
        password: my-password
        listen: '172.19.0.2:3310'

    storage-1:
      ansible_host: 172.19.0.3
      ansible_user: vagrant
      config:
        advertise_uri: '172.19.0.3:3301'
        http_port: 8081
```
